# Generated by Django 4.2.9 on 2024-01-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="to_be_deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
